// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the THIRD-PARTY file.

//! Virtual Machine Monitor that leverages the Linux Kernel-based Virtual Machine (KVM),
//! and other virtualization features to run a single lightweight micro-virtual
//! machine (microVM).
//#![deny(missing_docs)]

#[macro_use]
extern crate log;

/// Handles setup and initialization a `Vmm` object.
pub mod builder;
pub(crate) mod device_manager;
/// Dirty page bitmap for incremental snapshots.
#[cfg(target_os = "macos")]
pub mod dirty_bitmap;
/// Resource store for configured microVM resources.
pub mod resources;
/// Signal handling utilities.
#[cfg(target_os = "linux")]
pub mod signal_handler;
/// VM snapshot and restore support.
#[cfg(target_os = "macos")]
pub mod snapshot;
/// Wrappers over structures used to configure the VMM.
pub mod vmm_config;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use crate::linux::vstate;
#[cfg(target_os = "macos")]
mod macos;
mod terminal;
pub mod worker;

#[cfg(target_os = "macos")]
use macos::vstate;

use std::fmt::{Display, Formatter};
use std::io;
use std::os::unix::io::AsRawFd;
use std::sync::atomic::{AtomicI32, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

#[cfg(target_arch = "x86_64")]
use crate::device_manager::legacy::PortIODeviceManager;
use crate::device_manager::mmio::MMIODeviceManager;
use crate::vstate::VcpuEvent;
use crate::vstate::{Vcpu, VcpuHandle, VcpuResponse, Vm};

use arch::{ArchMemoryInfo, InitrdConfig};
#[cfg(target_os = "macos")]
use crossbeam_channel::Sender;
#[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
use devices::fdt;
use devices::legacy::IrqChip;
use devices::virtio::VmmExitObserver;
use devices::{BusDevice, DeviceType};
use kernel::cmdline::Cmdline as KernelCmdline;
use polly::event_manager::{self, EventManager, Subscriber};
use utils::epoll::{EpollEvent, EventSet};
use utils::eventfd::EventFd;
#[cfg(target_os = "macos")]
use vm_memory::Address;
use vm_memory::GuestMemoryMmap;

/// Success exit code.
pub const FC_EXIT_CODE_OK: u8 = 0;
/// Generic error exit code.
pub const FC_EXIT_CODE_GENERIC_ERROR: u8 = 1;
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
pub const FC_EXIT_CODE_UNEXPECTED_ERROR: u8 = 2;
/// Firecracker was shut down after intercepting a restricted system call.
pub const FC_EXIT_CODE_BAD_SYSCALL: u8 = 148;
/// Firecracker was shut down after intercepting `SIGBUS`.
pub const FC_EXIT_CODE_SIGBUS: u8 = 149;
/// Firecracker was shut down after intercepting `SIGSEGV`.
pub const FC_EXIT_CODE_SIGSEGV: u8 = 150;
/// Bad configuration for microvm's resources, when using a single json.
pub const FC_EXIT_CODE_BAD_CONFIGURATION: u8 = 152;
/// Command line arguments parsing error.
pub const FC_EXIT_CODE_ARG_PARSING: u8 = 153;

/// Errors associated with the VMM internal logic. These errors cannot be generated by direct user
/// input, but can result from bad configuration of the host (for example if Firecracker doesn't
/// have permissions to open the KVM fd).
#[derive(Debug)]
pub enum Error {
    /// This error is thrown by the minimal boot loader implementation.
    ConfigureSystem(arch::Error),
    /// Legacy devices work with Event file descriptors and the creation can fail because
    /// of resource exhaustion.
    #[cfg(target_arch = "x86_64")]
    CreateLegacyDevice(device_manager::legacy::Error),
    /// Cannot read from an Event file descriptor.
    EventFd(io::Error),
    /// Polly error wrapper.
    EventManager(event_manager::Error),
    /// I8042 Error.
    I8042Error(devices::legacy::I8042DeviceError),
    /// Cannot access kernel file.
    KernelFile(io::Error),
    /// Cannot open /dev/kvm. Either the host does not have KVM or Firecracker does not have
    /// permission to open the file descriptor.
    KvmContext(vstate::Error),
    #[cfg(target_arch = "x86_64")]
    /// Cannot add devices to the Legacy I/O Bus.
    LegacyIOBus(device_manager::legacy::Error),
    /// Cannot load command line.
    LoadCommandline(kernel::cmdline::Error),
    /// Cannot add a device to the MMIO Bus.
    RegisterMMIODevice(device_manager::mmio::Error),
    /// Write to the serial console failed.
    Serial(io::Error),
    #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
    /// Cannot generate or write FDT
    SetupFDT(devices::fdt::Error),
    /// Cannot create Timer file descriptor.
    TimerFd(io::Error),
    /// Vcpu error.
    Vcpu(vstate::Error),
    /// Cannot send event to vCPU.
    VcpuEvent(vstate::Error),
    /// Cannot create a vCPU handle.
    VcpuHandle(vstate::Error),
    /// vCPU pause failed.
    VcpuPause,
    /// vCPU resume failed.
    VcpuResume,
    /// Cannot spawn a new Vcpu thread.
    VcpuSpawn(std::io::Error),
    /// Vm error.
    Vm(vstate::Error),
    /// Error thrown by observer object on Vmm initialization.
    VmmObserverInit(utils::errno::Error),
    /// Error thrown by observer object on Vmm teardown.
    VmmObserverTeardown(utils::errno::Error),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        use self::Error::*;

        match self {
            ConfigureSystem(e) => write!(f, "System configuration error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            CreateLegacyDevice(e) => write!(f, "Error creating legacy device: {e:?}"),
            EventFd(e) => write!(f, "Event fd error: {e}"),
            EventManager(e) => write!(f, "Event manager error: {e:?}"),
            I8042Error(e) => write!(f, "I8042 error: {e}"),
            KernelFile(e) => write!(f, "Cannot access kernel file: {e}"),
            KvmContext(e) => write!(f, "Failed to validate KVM support: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            LegacyIOBus(e) => write!(f, "Cannot add devices to the legacy I/O Bus. {e}"),
            LoadCommandline(e) => write!(f, "Cannot load command line: {e}"),
            RegisterMMIODevice(e) => write!(f, "Cannot add a device to the MMIO Bus. {e}"),
            Serial(e) => write!(f, "Error writing to the serial console: {e:?}"),
            #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
            SetupFDT(e) => write!(f, "Error generating or writing FDT: {e:?}"),
            TimerFd(e) => write!(f, "Error creating timer fd: {e}"),
            Vcpu(e) => write!(f, "Vcpu error: {e}"),
            VcpuEvent(e) => write!(f, "Cannot send event to vCPU. {e:?}"),
            VcpuHandle(e) => write!(f, "Cannot create a vCPU handle. {e}"),
            VcpuPause => write!(f, "vCPUs pause failed."),
            VcpuResume => write!(f, "vCPUs resume failed."),
            VcpuSpawn(e) => write!(f, "Cannot spawn Vcpu thread: {e}"),
            Vm(e) => write!(f, "Vm error: {e}"),
            VmmObserverInit(e) => write!(
                f,
                "Error thrown by observer object on Vmm initialization: {e}"
            ),
            VmmObserverTeardown(e) => {
                write!(f, "Error thrown by observer object on Vmm teardown: {e}")
            }
        }
    }
}

/// Trait for objects that need custom initialization and teardown during the Vmm lifetime.
pub trait VmmEventsObserver {
    /// This function will be called during microVm boot.
    fn on_vmm_boot(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
    /// This function will be called on microVm teardown.
    fn on_vmm_stop(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
}

/// Shorthand result type for internal VMM commands.
pub type Result<T> = std::result::Result<T, Error>;

/// Contains the state and associated methods required for the Firecracker VMM.
pub struct Vmm {
    // Guest VM core resources.
    guest_memory: GuestMemoryMmap,
    arch_memory_info: ArchMemoryInfo,

    kernel_cmdline: KernelCmdline,

    vcpus_handles: Vec<VcpuHandle>,
    exit_evt: EventFd,
    vm: Vm,
    exit_observers: Vec<Arc<Mutex<dyn VmmExitObserver>>>,
    exit_code: Arc<AtomicI32>,

    // Guest VM devices.
    mmio_device_manager: MMIODeviceManager,
    #[cfg(target_arch = "x86_64")]
    pio_device_manager: PortIODeviceManager,
    #[cfg(target_os = "macos")]
    dirty_bitmaps: Vec<dirty_bitmap::DirtyBitmap>,

    // Interrupt controller state needed for snapshots.
    #[cfg(target_os = "macos")]
    vcpu_list: Arc<devices::legacy::VcpuList>,
    #[cfg(target_os = "macos")]
    intc: IrqChip,
}

impl Vmm {
    /// Gets the the specified bus device.
    pub fn get_bus_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<dyn BusDevice>> {
        self.mmio_device_manager.get_device(device_type, device_id)
    }

    /// Starts the microVM vcpus.
    pub fn start_vcpus(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        self.start_vcpus_paused(&mut vcpus)?;

        // The vcpus start off in the `Paused` state, let them run.
        self.resume_vcpus()?;

        Ok(())
    }

    /// Starts the microVM vcpus without resuming them.
    ///
    /// After this call vCPU threads exist but are sitting in their initial
    /// event loop waiting for Resume or RestoreState. Use this for cold
    /// restore from snapshot.
    pub fn start_vcpus_paused(&mut self, vcpus: &mut Vec<Vcpu>) -> Result<()> {
        Vcpu::register_kick_signal_handler();

        self.vcpus_handles.reserve(vcpus.len());

        for vcpu in vcpus.drain(..) {
            let mut vcpu = vcpu;
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());

            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }

        Ok(())
    }

    /// Sends a pause command to all vcpus and waits for confirmation.
    pub fn pause_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Pause)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Paused) => (),
                _ => return Err(Error::VcpuPause),
            }
        }
        Ok(())
    }

    /// Save all vCPU states. vCPUs must already be paused.
    #[cfg(target_os = "macos")]
    pub fn save_vcpu_states(&self) -> Result<Vec<hvf::Aarch64VcpuState>> {
        let mut states = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            states.push(handle.save_state().map_err(Error::Vcpu)?);
        }
        Ok(states)
    }

    /// Restore all vCPU states. vCPUs must already be paused.
    #[cfg(target_os = "macos")]
    pub fn restore_vcpu_states(&self, states: Vec<hvf::Aarch64VcpuState>) -> Result<()> {
        if states.len() != self.vcpus_handles.len() {
            return Err(Error::VcpuPause);
        }
        for (handle, state) in self.vcpus_handles.iter().zip(states.into_iter()) {
            handle.restore_state(state).map_err(Error::Vcpu)?;
        }
        Ok(())
    }

    /// Save interrupt controller state (pending IRQs + GIC registers) for snapshot.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    fn save_interrupt_controller_state(
        &self,
    ) -> std::result::Result<Option<Vec<u8>>, snapshot::SnapshotError> {
        let pending_irqs = self.vcpu_list.save_interrupt_state();
        let gic_registers = self.intc.lock().unwrap().save_snapshot_state();

        let ic_snapshot = snapshot::InterruptControllerSnapshot {
            pending_irqs,
            gic_registers,
        };

        let data = bincode::serialize(&ic_snapshot)
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;
        Ok(Some(data))
    }

    /// Restore interrupt controller state (pending IRQs + GIC registers) from snapshot.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    fn restore_interrupt_controller_state(
        &self,
        data: &[u8],
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let ic_snapshot: snapshot::InterruptControllerSnapshot =
            bincode::deserialize(data)
                .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;

        self.vcpu_list
            .restore_interrupt_state(&ic_snapshot.pending_irqs);

        if let Some(gic_data) = &ic_snapshot.gic_registers {
            self.intc.lock().unwrap().restore_snapshot_state(gic_data);
        }

        Ok(())
    }

    /// Sends a resume command to the vcpus.
    pub fn resume_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    /// Configures the system for boot.
    pub fn configure_system(
        &self,
        vcpus: &[Vcpu],
        _intc: &IrqChip,
        initrd: &Option<InitrdConfig>,
        _smbios_oem_strings: &Option<Vec<String>>,
    ) -> Result<()> {
        #[cfg(target_arch = "x86_64")]
        {
            let cmdline_len = if cfg!(feature = "tee") {
                arch::x86_64::layout::CMDLINE_SEV_SIZE
            } else {
                self.kernel_cmdline.len() + 1
            };

            arch::x86_64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                vm_memory::GuestAddress(arch::x86_64::layout::CMDLINE_START),
                cmdline_len,
                initrd,
                vcpus.len() as u8,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            let vcpu_mpidr = vcpus.iter().map(|cpu| cpu.get_mpidr()).collect();
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpu_mpidr,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            arch::aarch64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                _smbios_oem_strings,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "riscv64")]
        {
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpus.len() as u32,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;

            arch::riscv64::configure_system(&self.guest_memory, _smbios_oem_strings)
                .map_err(Error::ConfigureSystem)?;
        }

        Ok(())
    }

    /// Returns a reference to the guest memory.
    pub fn guest_memory(&self) -> &GuestMemoryMmap {
        &self.guest_memory
    }

    /// Returns a reference to the arch memory info.
    pub fn arch_memory_info(&self) -> &ArchMemoryInfo {
        &self.arch_memory_info
    }

    /// Create a full snapshot of the VM. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn create_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        // Save device state before vCPU state (Firecracker convention: device
        // save may trigger interrupts that should be captured in vCPU state).
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        let gic_state = self.save_interrupt_controller_state()?;

        snapshot::create_full_snapshot(
            path,
            &self.guest_memory,
            vcpu_states,
            device_states,
            gic_state,
            false, // TODO: get nested_enabled from VM config
        )
    }

    /// Restore a full snapshot into the running VM. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn restore_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let vmstate = snapshot::load_vmstate(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
        )?;

        // Quiesce all async device workers before overwriting guest memory.
        // Workers may hold VolatileSliceGuard pointers into guest RAM; if we
        // overwrite memory while they're mid-operation, they'll corrupt the
        // restored state (e.g. writing stale used-ring entries → NETDEV WATCHDOG).
        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::load_memory(&self.guest_memory, &path.join("memory"))?;

        // Phase 1: Restore all state without spawning any threads.
        // Device state is deserialized but activate() is deferred.
        if let Some(gic_data) = &vmstate.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }
        self.mmio_device_manager
            .restore_all_device_states(&vmstate.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        // Phase 2: Now that all state is loaded, activate devices (spawning
        // threads) and kick workers. Threads can safely fire IRQs because
        // interrupt controller state is already in place.
        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        self.restore_vcpu_states(vmstate.vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;
        Ok(())
    }

    /// Enable dirty page tracking. vCPUs must be paused.
    /// After this call, all RAM writes will be tracked via write-protect faults.
    #[cfg(target_os = "macos")]
    pub fn enable_dirty_tracking(&mut self) -> Result<()> {
        use vm_memory::{GuestMemory, GuestMemoryRegion};

        self.dirty_bitmaps.clear();
        let mut ram_regions = Vec::new();
        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            self.dirty_bitmaps
                .push(dirty_bitmap::DirtyBitmap::new(base, size));
            ram_regions.push((base, size));

            Vm::protect_memory(base, size, true, false, true).map_err(Error::Vm)?;
        }

        let bitmaps_ptr = &self.dirty_bitmaps as *const Vec<dirty_bitmap::DirtyBitmap>;
        for handle in self.vcpus_handles.iter() {
            let bitmaps_ptr_copy = bitmaps_ptr as usize;
            let ram_regions_clone = ram_regions.clone();

            let callback: hvf::DirtyCallback = Box::new(move |page_addr| {
                let bitmaps =
                    unsafe { &*(bitmaps_ptr_copy as *const Vec<dirty_bitmap::DirtyBitmap>) };
                for bitmap in bitmaps.iter() {
                    if bitmap.contains(page_addr) {
                        bitmap.mark_dirty(page_addr);
                        return;
                    }
                }
            });

            let config = crate::vstate::DirtyTrackingConfig {
                ram_regions: ram_regions_clone,
                dirty_callback: callback,
            };

            handle
                .send_event(VcpuEvent::EnableDirtyTracking(Box::new(config)))
                .map_err(Error::VcpuEvent)?;
        }

        Ok(())
    }

    /// Disable dirty page tracking. vCPUs must be paused.
    #[cfg(target_os = "macos")]
    pub fn disable_dirty_tracking(&mut self) -> Result<()> {
        use vm_memory::{GuestMemory, GuestMemoryRegion};

        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            Vm::protect_memory(base, size, true, true, true).map_err(Error::Vm)?;
        }

        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::DisableDirtyTracking)
                .map_err(Error::VcpuEvent)?;
        }

        self.dirty_bitmaps.clear();
        Ok(())
    }

    /// Create an incremental snapshot (dirty pages only). vCPUs must be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn create_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        use vm_memory::{GuestAddress, GuestMemory, GuestMemoryRegion};

        // Save device state before vCPU state (Firecracker convention).
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        let gic_state = self.save_interrupt_controller_state()?;

        let mut dirty_pages = Vec::new();
        for bitmap in &self.dirty_bitmaps {
            let dirty_addrs = bitmap.drain_dirty_pages();
            for addr in dirty_addrs {
                let host_ptr = self
                    .guest_memory
                    .get_host_address(GuestAddress(addr))
                    .map_err(|e| {
                        snapshot::SnapshotError::Serialize(format!(
                            "Invalid guest address for dirty page 0x{addr:x}: {e}"
                        ))
                    })?;
                let page_data = unsafe {
                    std::slice::from_raw_parts(host_ptr, dirty_bitmap::PAGE_SIZE as usize)
                };
                dirty_pages.push(snapshot::DirtyPage {
                    guest_addr: addr,
                    data: page_data.to_vec(),
                });
            }
        }

        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            Vm::protect_memory(base, size, true, false, true).map_err(|e| {
                snapshot::SnapshotError::Io(std::io::Error::new(
                    std::io::ErrorKind::Other,
                    format!("{e}"),
                ))
            })?;
        }

        let incremental = snapshot::IncrementalSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                nested_enabled: false,
            },
            vcpu_states,
            device_states,
            dirty_pages,
            gic_state,
        };

        snapshot::save_incremental_snapshot(&incremental, path)
    }

    /// Restore an incremental snapshot. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn restore_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let incremental = snapshot::load_incremental_snapshot(path)?;
        snapshot::validate_header_for_vm(
            &incremental.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
        )?;

        // Quiesce all async device workers before overwriting guest memory.
        // Same race as restore_snapshot: workers may hold raw pointers into
        // guest RAM during in-flight I/O.
        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::apply_dirty_pages(&self.guest_memory, &incremental.dirty_pages)?;

        // Phase 1: Restore all state without spawning any threads.
        if let Some(gic_data) = &incremental.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }
        self.mmio_device_manager
            .restore_all_device_states(&incremental.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        // Phase 2: Activate devices (if needed) and kick workers.
        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        self.restore_vcpu_states(incremental.vcpu_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
            })?;
        Ok(())
    }

    /// Injects CTRL+ALT+DEL keystroke combo in the i8042 device.
    #[cfg(target_arch = "x86_64")]
    pub fn send_ctrl_alt_del(&mut self) -> Result<()> {
        self.pio_device_manager
            .i8042
            .lock()
            .expect("i8042 lock was poisoned")
            .trigger_ctrl_alt_del()
            .map_err(Error::I8042Error)
    }

    /// Waits for all vCPUs to exit and terminates the Firecracker process.
    pub fn stop(&mut self, exit_code: i32) {
        info!("Vmm is stopping with exit_code={exit_code}");

        for observer in &self.exit_observers {
            observer
                .lock()
                .expect("Poisoned mutex for exit observer")
                .on_vmm_exit();
        }

        // Exit from Firecracker using the provided exit code. Safe because we're terminating
        // the process anyway.
        unsafe {
            libc::_exit(exit_code);
        }
    }

    /// Returns a reference to the inner KVM Vm object.
    pub fn kvm_vm(&self) -> &Vm {
        &self.vm
    }

    #[cfg(target_os = "macos")]
    pub fn add_mapping(
        &self,
        reply_sender: Sender<bool>,
        host_addr: u64,
        guest_addr: u64,
        len: u64,
    ) {
        self.vm
            .add_mapping(reply_sender, host_addr, guest_addr, len);
    }

    #[cfg(target_os = "macos")]
    pub fn remove_mapping(&self, reply_sender: Sender<bool>, guest_addr: u64, len: u64) {
        self.vm.remove_mapping(reply_sender, guest_addr, len);
    }
}

impl Subscriber for Vmm {
    /// Handle a read event (EPOLLIN).
    fn process(&mut self, event: &EpollEvent, _: &mut EventManager) {
        let source = event.fd();
        let event_set = event.event_set();

        if source == self.exit_evt.as_raw_fd() && event_set == EventSet::IN {
            debug!("Vmm: exit_evt fired, shutting down");
            let _ = self.exit_evt.read();
            // Query each vcpu for the exit_code.
            // If the exit_code can't be found on any vcpu, it means that the exit signal
            // has been issued by the i8042 controller in which case we exit with
            // FC_EXIT_CODE_OK.
            //
            // The exit code set up by the guest takes preference over the one reported
            // by either a vcpu or the i8042 controller.
            let vcpu_exit_code = self
                .vcpus_handles
                .iter()
                .find_map(|handle| match handle.response_receiver().try_recv() {
                    Ok(VcpuResponse::Exited(exit_code)) => Some(exit_code),
                    _ => None,
                })
                .unwrap_or(FC_EXIT_CODE_OK);
            let vmm_exit_code = self.exit_code.load(Ordering::SeqCst);
            let exit_code = if vmm_exit_code != i32::MAX {
                debug!("using vmm exit code: {vmm_exit_code}");
                vmm_exit_code
            } else {
                debug!("using vcpu exit code: {vcpu_exit_code}");
                vcpu_exit_code as i32
            };
            self.stop(exit_code);
        } else {
            error!("Spurious EventManager event for handler: Vmm");
        }
    }

    fn interest_list(&self) -> Vec<EpollEvent> {
        vec![EpollEvent::new(
            EventSet::IN,
            self.exit_evt.as_raw_fd() as u64,
        )]
    }
}
