[package]
name = "net-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.30", features = ["fs", "socket"] }
log = "0.4.0"
libc = ">=0.2.39"
crossbeam-channel = "0.5.15"
bytes = "1"
mio = { version = "1.0.4", features = ["net", "os-ext", "os-poll"] }
socket2 = { version = "0.5.10", features = ["all"] }
pnet = "0.35.0"
rand = "0.9.1"
tracing = { version = "0.1.41" }                                     #, features = ["release_max_level_debug"] }
utils = { path = "../utils" }

[dev-dependencies]
tracing-subscriber = "0.3.19"
lazy_static = "*"
tempfile = "*"
